name: Deployment to AWS EB
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: event-organizer-project/github-actions/.github/workflows/dotnet_build.yml@master

  test:
    needs: build
    uses: event-organizer-project/github-actions/.github/workflows/dotnet_test.yml@master

  deploy:
    needs: [ build, test ]
    uses: event-organizer-project/github-actions/.github/workflows/dotnet_deploy.yml@master